version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost.crt:/etc/ssl/certs/localhost.crt
      - ./localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./client
    depends_on:
      - backend

  backend:
    build: ./server
    command: flask run --host=0.0.0.0
    env_file:
      - .env
    ports:
      - "5000:5000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"