"""empty message

Revision ID: 82700a2240a4
Revises: 9dd11fde6d94
Create Date: 2024-01-07 14:50:57.689153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82700a2240a4'
down_revision = '9dd11fde6d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combination', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('combination')

    # ### end Alembic commands ###
